### ISSUE TITLE
Option to disable / enable it on demand

### ISSUE THREAD

**Issue by vizcay** [fphilipe/i18n-debug#1]
Hey.. nice simple gem! helped me to debug a few issues related to translation in my rails forms.

The only caveat in my opinion is that is "on" all times by default, now that I've fixed my issue I found that the extra debug info makes too much noise in my logs, but the "simple" option to disable the gem is to comment it at the Gemfile.

I will just fork and modify line 43 to

``` ruby
Backend::Simple.include(Debug::Hook) if ENV["WITH_I18N_DEBUG"]
```

so for example I'm able to do:

```
$ WITH_I18N_DEBUG=true bundle exec rails s
```

just in case I need it.

**Comment by fphilipe** [comment]
The way I do it is to add it to the Gemfile whenever I need it :smile:

**Comment by yapus** [comment]
`config/environments/development.rb`
```
  I18n::Debug.logger = ->(*args) { nil } if ENV["WITH_I18N_DEBUG"]
```

**Comment by martyciz** [comment]
Hi, I think this is relevant request and should be re-opened :)

I suggest preserving existing behaviour, but adding line:
```
Backend::Simple.include(Debug::Hook) unless ENV["DISABLE_I18N_DEBUG"]
```

And mention this option in README.

My use case:
Two developers work on the same project, but one of them doesn't need to see I18n debug in logs, so she just turns it off. For a long term changing Gemfile wouldn't work, because it's a shared repository.

**Comment by amorozdna** [comment]
I agree with the comment above.

My case is almost the same: multiple devs work on the same repo, not anyone need this kind of debug messages in the logs.
